src/ABPCMS.Web/Models/Layout/RightSideBarViewModel.cs
using ABPCMS.Configuration.Ui;

namespace ABPCMS.Web.Models.Layout
{
    public class RightSideBarViewModel
    {
        public UiThemeInfo CurrentTheme { get; set; }
    }
}

src/ABPCMS.Web/Models/Layout/SideBarNavViewModel.cs
using Abp.Application.Navigation;

namespace ABPCMS.Web.Models.Layout
{
    public class SideBarNavViewModel
    {
        public UserMenu MainMenu { get; set; }

        public string ActiveMenuItemName { get; set; }
    }
}

src/ABPCMS.Web/Models/Layout/SideBarUserAreaViewModel.cs
using ABPCMS.Sessions.Dto;

namespace ABPCMS.Web.Models.Layout
{
    public class SideBarUserAreaViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }

        public bool IsMultiTenancyEnabled { get; set; }

        public string GetShownLoginName()
        {
            var userName = "<span id=\"HeaderCurrentUserName\">" + LoginInformations.User.UserName + "</span>";

            if (!IsMultiTenancyEnabled)
            {
                return userName;
            }

            return LoginInformations.Tenant == null
                ? ".\\" + userName
                : LoginInformations.Tenant.TenancyName + "\\" + userName;
        }
    }
}

src/ABPCMS.Web/Controllers/LayoutController.cs
using System.Linq;
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Configuration;
using Abp.Configuration.Startup;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using ABPCMS.Configuration;
using ABPCMS.Configuration.Ui;
using ABPCMS.Sessions;
using ABPCMS.Web.Models;
using ABPCMS.Web.Models.Layout;
using Abp.Auditing;

namespace ABPCMS.Web.Controllers
{
    public class LayoutController : ABPCMSControllerBase
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly ISessionAppService _sessionAppService;
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly ILanguageManager _languageManager;

        public LayoutController(
            IUserNavigationManager userNavigationManager,
            ISessionAppService sessionAppService,
            IMultiTenancyConfig multiTenancyConfig,
            ILanguageManager languageManager)
        {
            _userNavigationManager = userNavigationManager;
            _sessionAppService = sessionAppService;
            _multiTenancyConfig = multiTenancyConfig;
            _languageManager = languageManager;
        }

        [ChildActionOnly]
        public PartialViewResult SideBarNav(string activeMenu = "")
        {
            var model = new SideBarNavViewModel
            {
                MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.ToUserIdentifier())),
                ActiveMenuItemName = activeMenu
            };

            return PartialView("_LeftSideMenus", model);
        }

        [ChildActionOnly]
        public PartialViewResult SideBarUserArea()
        {
            var model = new SideBarUserAreaViewModel
            {
                LoginInformations = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations()),
                IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
            };

            return PartialView("_SideBarUserArea", model);
        }

        [ChildActionOnly]
        public PartialViewResult LanguageSelection()
        {
            var model = new LanguageSelectionViewModel
            {
                CurrentLanguage = _languageManager.CurrentLanguage,
                Languages = _languageManager.GetLanguages()
            };

            return PartialView("_LanguageSelection", model);
        }

        [ChildActionOnly]
        public PartialViewResult RightSideBar()
        {
            var themeName = SettingManager.GetSettingValue(AppSettingNames.UiTheme);

            var viewModel = new RightSideBarViewModel
            {
                CurrentTheme = UiThemes.All.FirstOrDefault(t => t.CssClass == themeName)
            };

            return PartialView("_RightSideBar", viewModel);
        }

        [DisableAuditing]
        public ActionResult _Layout()
        {
            return View();
        }
        [DisableAuditing]
        public ActionResult _LeftSideMenus(string activeMenu = "")
        {
            var model = new SideBarNavViewModel
            {
                MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.ToUserIdentifier())),
                ActiveMenuItemName = activeMenu
            };
            return PartialView("_LeftSideMenus", model);
        }
        [DisableAuditing]
        public ActionResult _MainFooter()
        {
            return PartialView("_MainFooter");
        }
        [DisableAuditing]
        public ActionResult _MainHeader()
        {
            return PartialView("_MainHeader");
        }

    }
}

src/ABPCMS.Web/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Configuration
@using Abp.Timing
@using Abp.Web.Mvc.Extensions
@using ABPCMS
@using ABPCMS.Configuration
@{
    Layout = null;
    SetAntiForgeryCookie();
    var uiTheme = SettingManager.GetSettingValue(AppSettingNames.UiTheme);
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>AdminLTE 2 | Dashboard</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    @Styles.Render("~/Bundles/vendor/css")

    @RenderSection("styles", required: false)

    <script src="~/Scripts/jquery-3.2.1.js"></script>

    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport' />
    <!-- Bootstrap 3.3.4 -->
    @*<script src="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/bootstrap/js/bootstrap.js"></script>*@
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <!-- FontAwesome 4.3.0 -->
    <!-- Ionicons 2.0.0 -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/dist/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/plugins/iCheck/flat/blue.css" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/plugins/morris/morris.css" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/plugins/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
    <!-- Date Picker -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/plugins/datepicker/datepicker3.css" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/plugins/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
    <!-- bootstrap wysihtml5 - text editor -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet" type="text/css" />

    <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    <!-- jQuery 2.2.3 -->
    <link href="~/Scripts/Content/bootstrap-table/bootstrap-table.css" rel="stylesheet" />
   @* <script src="~/Scripts/Content/bootstrap-table/bootstrap-table.js"></script>
    <script src="~/Scripts/Content/bootstrap-table/locale/bootstrap-table-zh-CN.js"></script>
    <link href="~/Scripts/Toastr/toastr.css" rel="stylesheet" />
    <script src="~/Scripts/Toastr/toastr.min.js"></script>
    <link href="~/Abp/Framework/styles/abp.css" rel="stylesheet" />
    <script src="~/Abp/Framework/scripts/abp.js"></script>
    <script src="~/Abp/Framework/scripts/libs/abp.jquery.js"></script>*@

    <style type="text/css">
        body {
            font-family: verdana,helvetica,arial,sans-serif;
            padding: 0 !important;
            margin: 0;
        }

        .content {
            min-height: 700px;
            height: auto !important;
        }
        .wrapper {
            min-height: 100%;
            height: 1100px !important;
        }

        .main-header .navbar-custom-menu, .main-header .navbar-right {
            float: right !important;
        }

        vendor-prefixes.less:76 * {
            box-sizing: border-box !important;
        }

        .open:not(.dropup) > .animated-dropdown-menu {
            backface-visibility: visible !important;
            .animation(flipInX .7s both) !important;
        }
        .main-header .navbar-custom-menu, .main-header .navbar-right {
            float: right !important;
            margin-right: 300px !important;
        }

        .navbar-fixed-top .navbar-collapse, .navbar-static-top .navbar-collapse, .navbar-fixed-bottom .navbar-collapse {
            padding-right: 0;
            padding-left: 0;
            margin-top: -45px;
            margin-left: 25px;
        }

        /*.sidebar {
            display: none !important;

        }*/

        .content {
            min-height: 700px ;
            height: auto !important;
        }

        /*.content {
            min-height: 250px !important;
            padding: 15px !important;
            margin-right: auto !important;
            margin-left: auto !important;
            padding-left: 15px !important;
            padding-right: 15px !important;
        }
        .panel-body {
            padding: 15px;
            margin-top: -60px !important;
        }*/
        /*section.content {
            margin: 100px 15px 0 315px;
            -moz-transition: 0.5s;
            -o-transition: 0.5s;
            -webkit-transition: 0.5s;
            transition: 0.5s;
            margin-left: -5px;
        }*/


    </style>


    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';

    </script>

</head>

<body class="hold-transition skin-blue sidebar-mini"  >

    <div class="wrapper">
        @Html.Action("_MainHeader", "Layout")
        @Html.Action("SideBarNav", "Layout", new { activeMenu = ViewBag.ActiveMenu })

        <div class="content-wrapper">
            @RenderBody()
        </div>
        @Html.Action("_MainFooter", "Layout")
        <div class="control-sidebar-bg"></div>
    </div>
    @*<script src="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/dist/js/app.min.js"></script>*@


    @Scripts.Render("~/Bundles/vendor/js/bottom")

    <script>
        //Localizing momentjs
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- SignalR scripts -->
    <script src="~/signalr/hubs"></script>
    @Html.IncludeScript("~/Abp/Framework/scripts/libs/abp.signalr.js")

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)

</body>
</html>

src/ABPCMS.Web/Views/Shared/_Layout1.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Configuration
@using Abp.Timing
@using Abp.Web.Mvc.Extensions
@using ABPCMS
@using ABPCMS.Configuration
@{
    Layout = null;
    SetAntiForgeryCookie();
    var uiTheme = SettingManager.GetSettingValue(AppSettingNames.UiTheme);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="~/favicon.ico">

    <title>ABPCMS</title>

    @Styles.Render("~/Bundles/vendor/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>
</head>
<body class="@("theme-" + uiTheme)">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-red">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>Please wait...</p>
        </div>
    </div>
    <!-- #END# Page Loader -->
    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>
    <!-- #END# Overlay For Sidebars -->
    <!-- Search Bar -->
    <div class="search-bar">
        <div class="search-icon">
            <i class="material-icons">search</i>
        </div>
        <input type="text" placeholder="START TYPING...">
        <div class="close-search">
            <i class="material-icons">close</i>
        </div>
    </div>
    <!-- #END# Search Bar -->
    <!-- Top Bar -->
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
                <a href="javascript:void(0);" class="bars"></a>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index"><i class="fa fa-cubes"></i> ABPCMS</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <!-- Call Search -->
                    <li><a href="javascript:void(0);" class="js-search" data-close="true"><i class="material-icons">search</i></a></li>
                    <!-- #END# Call Search -->
                    @Html.Action("LanguageSelection", "Layout")

                    <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="material-icons">more_vert</i></a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- #Top Bar -->
    <section>
        <aside id="leftsidebar" class="sidebar">

            @Html.Action("SideBarUserArea", "Layout")
            @Html.Action("SideBarNav", "Layout", new { activeMenu = ViewBag.ActiveMenu })

            <!-- Footer -->
            <div class="legal">
                <div class="copyright">
                    &copy; @DateTime.Now.Year <a href="javascript:void(0);">ABPCMS</a>.
                </div>
                <div class="version">
                    <b>Version </b> @AppVersionHelper.Version [@AppVersionHelper.ReleaseDate.ToString("yyyyMMdd")]
                </div>
            </div>
            <!-- #Footer -->
        </aside>

        @Html.Action("RightSideBar", "Layout")

    </section>

    <section class="content">
        <div class="container-fluid">
            @RenderBody()
        </div>
    </section>

    @Scripts.Render("~/Bundles/vendor/js/bottom")

    <script>
        //Localizing momentjs
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- SignalR scripts -->
    <script src="~/signalr/hubs"></script>
    @Html.IncludeScript("~/Abp/Framework/scripts/libs/abp.signalr.js")

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

src/ABPCMS.Web/Views/Shared/_Layout2.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Configuration
@using Abp.Timing
@using Abp.Web.Mvc.Extensions
@using ABPCMS
@using ABPCMS.Configuration
@{
    Layout = null;
    SetAntiForgeryCookie();
    var uiTheme = SettingManager.GetSettingValue(AppSettingNames.UiTheme);
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <title>AdminLTE 2 | Dashboard</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <script src="~/Scripts/jquery-2.2.0.js"></script>
    <script src="~/Scripts/jquery-2.2.0.min.js"></script>

    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport' />
    <!-- Bootstrap 3.3.4 -->
    <script src="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/bootstrap/js/bootstrap.js"></script>
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <!-- FontAwesome 4.3.0 -->
    <!-- Ionicons 2.0.0 -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/dist/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/plugins/iCheck/flat/blue.css" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/plugins/morris/morris.css" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/plugins/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
    <!-- Date Picker -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/plugins/datepicker/datepicker3.css" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/plugins/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
    <!-- bootstrap wysihtml5 - text editor -->
    <link href="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet" type="text/css" />

    <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    <!-- jQuery 2.2.3 -->
    <link href="~/Scripts/Content/bootstrap-table/bootstrap-table.css" rel="stylesheet" />
    <script src="~/Scripts/Content/bootstrap-table/bootstrap-table.js"></script>
    <script src="~/Scripts/Content/bootstrap-table/locale/bootstrap-table-zh-CN.js"></script>
    <link href="~/Scripts/Toastr/toastr.css" rel="stylesheet" />
    <script src="~/Scripts/Toastr/toastr.min.js"></script>
    <script src="~/Abp/Framework/scripts/abp.js"></script>
    <script src="~/Abp/Framework/scripts/libs/abp.jquery.js"></script>
    @Styles.Render("~/Bundles/vendor/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <style type="text/css">
        body {
            font-family: verdana,helvetica,arial,sans-serif;
            padding: 0 !important;
            margin: 0;
        }

        .content {
            min-height: 700px;
            height: auto !important;
        }
    </style>

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';

    </script>

</head>

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        @Html.Action("_MainHeader", "Layout")
        @Html.Action("SideBarNav", "Layout", new { activeMenu = ViewBag.ActiveMenu })

        <div class="content-wrapper">
            @RenderBody()
        </div>
        @Html.Action("_MainFooter", "Layout")
        <div class="control-sidebar-bg"></div>
    </div>
    <script src="~/Scripts/AdminLTE-2.1.1/AdminLTE-2.1.1/dist/js/app.min.js"></script>


    @Scripts.Render("~/Bundles/vendor/js/bottom")

    <script>
        //Localizing momentjs
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- SignalR scripts -->
    <script src="~/signalr/hubs"></script>
    @Html.IncludeScript("~/Abp/Framework/scripts/libs/abp.signalr.js")

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)

</body>
</html>